# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8658735b55f016e03d223145fa2d80cfc78d6e505b660bb7b1de59c12449821c206540c2514db1239802b7d11b987adf8c8ceacfa0298c88e5ea067887a0c49

test:
  secret_key_base: 40f9836b162f799a9cd47a5ef24b57cf1e955fb5b678fa5a270df3d524b094610484c156f240618c9d073818923b7e285ea6b580940de199d7a62a816222c536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
